"""Connect Video to User with UUID foreign key

Revision ID: bef99fd0a467
Revises: 25fa189c30e1
Create Date: 2025-09-19 13:16:53.365226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bef99fd0a467'
down_revision: Union[str, Sequence[str], None] = '25fa189c30e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'videos', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.drop_column('videos', 'user_id')
    # ### end Alembic commands ###
